/**
 * Seed: Tax codes for Form 1065 (Partnership) — all activity types
 * Software codes are representative; verify against actual software before production use.
 */

// software_code lookup: [ultratax, cch, lacerte, gosystem]
const SW = {
  // 1065 Business — Page 1
  GROSS_RECEIPTS:          ['1065-1a',  '1065_GR',  '100', 'P1-GR'],
  RETURNS_ALLOWANCES:      ['1065-1b',  '1065_RA',  '101', 'P1-RA'],
  COST_OF_GOODS_SOLD:      ['1065-2',   '1065_CGS', '102', 'P1-CGS'],
  OTHER_INCOME:            ['1065-7',   '1065_OI',  '107', 'P1-OI'],
  SALARIES_WAGES:          ['1065-9',   '1065_SW',  '110', 'P1-SW'],
  GUARANTEED_PAYMENTS:     ['1065-10',  '1065_GP',  '111', 'P1-GP'],
  REPAIRS_MAINTENANCE:     ['1065-11',  '1065_RM',  '112', 'P1-RM'],
  BAD_DEBTS:               ['1065-12',  '1065_BD',  '113', 'P1-BD'],
  RENT:                    ['1065-13',  '1065_RNT', '114', 'P1-RNT'],
  TAXES_LICENSES:          ['1065-14',  '1065_TL',  '115', 'P1-TL'],
  INTEREST_EXPENSE:        ['1065-15',  '1065_INT', '116', 'P1-INT'],
  DEPRECIATION:            ['1065-16a', '1065_DEP', '117', 'P1-DEP'],
  DEPLETION:               ['1065-17',  '1065_DPL', '118', 'P1-DPL'],
  RETIREMENT_PLANS:        ['1065-18',  '1065_RET', '119', 'P1-RET'],
  EMPLOYEE_BENEFITS:       ['1065-19',  '1065_EB',  '120', 'P1-EB'],
  OTHER_DEDUCTIONS:        ['1065-20',  '1065_OD',  '121', 'P1-OD'],
  // 1065 Schedule K
  K1_INTEREST_INCOME:      ['1065-K5',  '1065_K5',  '150', 'SK-5'],
  K1_ORDINARY_DIVIDENDS:   ['1065-K6a', '1065_K6a', '151', 'SK-6A'],
  K1_QUALIFIED_DIVIDENDS:  ['1065-K6b', '1065_K6b', '152', 'SK-6B'],
  K1_ROYALTIES:            ['1065-K7',  '1065_K7',  '153', 'SK-7'],
  K1_NET_ST_CAP_GAIN_LOSS: ['1065-K8',  '1065_K8',  '154', 'SK-8'],
  K1_NET_LT_CAP_GAIN_LOSS: ['1065-K9a', '1065_K9a', '155', 'SK-9A'],
  K1_UNRECAPTURED_SEC1250: ['1065-K9c', '1065_K9c', '156', 'SK-9C'],
  K1_NET_SEC1231_GAIN_LOSS:['1065-K10', '1065_K10', '157', 'SK-10'],
  K1_OTHER_INCOME_LOSS:    ['1065-K11', '1065_K11', '158', 'SK-11'],
  K1_SEC179_DEDUCTION:     ['1065-K12', '1065_K12', '159', 'SK-12'],
  K1_OTHER_DEDUCTIONS:     ['1065-K13', '1065_K13', '160', 'SK-13'],
  K1_CHARITABLE_CONTRIB:   ['1065-K13a','1065_K13a','161', 'SK-13A'],
  K1_INVESTMENT_INT_EXP:   ['1065-K13b','1065_K13b','162', 'SK-13B'],
  K1_FOREIGN_TAX_CREDIT:   ['1065-K16', '1065_K16', '163', 'SK-16'],
  K1_AMT_ITEMS:            ['1065-K17', '1065_K17', '164', 'SK-17'],
  K1_TAX_EXEMPT_INT:       ['1065-K18a','1065_K18a','165', 'SK-18A'],
  K1_NONDEDUCTIBLE_EXP:    ['1065-K18b','1065_K18b','166', 'SK-18B'],
  K1_DISTRIBUTIONS:        ['1065-K19', '1065_K19', '167', 'SK-19'],
  // 1065 Balance Sheet
  BS_CASH:                 ['1065-L1',  '1065_L1',  '200', 'SL-1'],
  BS_TRADE_NOTES_AR:       ['1065-L2a', '1065_L2a', '201', 'SL-2A'],
  BS_ALLOWANCE_BAD_DEBTS:  ['1065-L2b', '1065_L2b', '202', 'SL-2B'],
  BS_INVENTORIES:          ['1065-L3',  '1065_L3',  '203', 'SL-3'],
  BS_US_GOVT_OBLIGATIONS:  ['1065-L4',  '1065_L4',  '204', 'SL-4'],
  BS_TAX_EXEMPT_SECURITIES:['1065-L5',  '1065_L5',  '205', 'SL-5'],
  BS_OTHER_CURRENT_ASSETS: ['1065-L6',  '1065_L6',  '206', 'SL-6'],
  BS_LOANS_TO_PARTNERS:    ['1065-L7',  '1065_L7',  '207', 'SL-7'],
  BS_MORTGAGE_RE_LOANS:    ['1065-L8',  '1065_L8',  '208', 'SL-8'],
  BS_OTHER_INVESTMENTS:    ['1065-L9',  '1065_L9',  '209', 'SL-9'],
  BS_BUILDINGS_LAND:       ['1065-L10a','1065_L10a','210', 'SL-10A'],
  BS_ACCUM_DEPRECIATION:   ['1065-L10b','1065_L10b','211', 'SL-10B'],
  BS_DEPLETABLE_ASSETS:    ['1065-L11a','1065_L11a','212', 'SL-11A'],
  BS_ACCUM_DEPLETION:      ['1065-L11b','1065_L11b','213', 'SL-11B'],
  BS_LAND:                 ['1065-L12', '1065_L12', '214', 'SL-12'],
  BS_INTANGIBLE_ASSETS:    ['1065-L13a','1065_L13a','215', 'SL-13A'],
  BS_ACCUM_AMORTIZATION:   ['1065-L13b','1065_L13b','216', 'SL-13B'],
  BS_OTHER_ASSETS:         ['1065-L14', '1065_L14', '217', 'SL-14'],
  BS_ACCOUNTS_PAYABLE:     ['1065-L15', '1065_L15', '220', 'SL-15'],
  BS_NOTES_PAYABLE_LT1YR:  ['1065-L16', '1065_L16', '221', 'SL-16'],
  BS_OTHER_CURRENT_LIAB:   ['1065-L17', '1065_L17', '222', 'SL-17'],
  BS_LOANS_FROM_PARTNERS:  ['1065-L18', '1065_L18', '223', 'SL-18'],
  BS_MORTGAGES_GT1YR:      ['1065-L19', '1065_L19', '224', 'SL-19'],
  BS_OTHER_LIABILITIES:    ['1065-L20', '1065_L20', '225', 'SL-20'],
  BS_PARTNER_CAPITAL:      ['1065-L21', '1065_L21', '226', 'SL-21'],
  // M-1
  M1_NET_INCOME_BOOKS:     ['1065-M1-1','1065_M1_1','250', 'M1-1'],
  M1_INCOME_RTN_NOT_BOOKS: ['1065-M1-2','1065_M1_2','251', 'M1-2'],
  M1_GUARANTEED_PMTS_M1:   ['1065-M1-3','1065_M1_3','252', 'M1-3'],
  M1_EXP_BOOKS_NOT_RTN:    ['1065-M1-4','1065_M1_4','253', 'M1-4'],
  M1_INC_BOOKS_NOT_RTN:    ['1065-M1-5','1065_M1_5','254', 'M1-5'],
  M1_DED_RTN_NOT_BOOKS:    ['1065-M1-6','1065_M1_6','255', 'M1-6'],
  // M-2
  M2_BEGINNING_CAPITAL:    ['1065-M2-1','1065_M2_1','260', 'M2-1'],
  M2_CAPITAL_CONTRIBUTED:  ['1065-M2-2','1065_M2_2','261', 'M2-2'],
  M2_NET_INCOME_M2:        ['1065-M2-3','1065_M2_3','262', 'M2-3'],
  M2_OTHER_INCREASES:      ['1065-M2-4','1065_M2_4','263', 'M2-4'],
  M2_DISTRIBUTIONS_CASH:   ['1065-M2-6','1065_M2_6','264', 'M2-6'],
  M2_DISTRIBUTIONS_PROP:   ['1065-M2-7','1065_M2_7','265', 'M2-7'],
  M2_OTHER_DECREASES:      ['1065-M2-8','1065_M2_8','266', 'M2-8'],
  // Rental (Form 8825)
  RENTAL_GROSS_RENTS:      ['8825-1',   '8825_GR',  '300', 'R-1'],
  RENTAL_OTHER_INCOME:     ['8825-2',   '8825_OI',  '301', 'R-2'],
  RENTAL_ADVERTISING:      ['8825-3a',  '8825_ADV', '310', 'R-3A'],
  RENTAL_AUTO_TRAVEL:      ['8825-3b',  '8825_AT',  '311', 'R-3B'],
  RENTAL_CLEANING_MAINT:   ['8825-3c',  '8825_CM',  '312', 'R-3C'],
  RENTAL_COMMISSIONS:      ['8825-3d',  '8825_COM', '313', 'R-3D'],
  RENTAL_INSURANCE:        ['8825-3e',  '8825_INS', '314', 'R-3E'],
  RENTAL_LEGAL_PROF:       ['8825-3f',  '8825_LP',  '315', 'R-3F'],
  RENTAL_MGMT_FEES:        ['8825-3g',  '8825_MF',  '316', 'R-3G'],
  RENTAL_MORTGAGE_INT:     ['8825-3h',  '8825_MI',  '317', 'R-3H'],
  RENTAL_OTHER_INT:        ['8825-3i',  '8825_OIT', '318', 'R-3I'],
  RENTAL_REPAIRS:          ['8825-3j',  '8825_REP', '319', 'R-3J'],
  RENTAL_SUPPLIES:         ['8825-3k',  '8825_SUP', '320', 'R-3K'],
  RENTAL_TAXES:            ['8825-3l',  '8825_TAX', '321', 'R-3L'],
  RENTAL_UTILITIES:        ['8825-3m',  '8825_UTL', '322', 'R-3M'],
  RENTAL_DEPRECIATION:     ['8825-3n',  '8825_DEP', '323', 'R-3N'],
  RENTAL_OTHER_EXPENSES:   ['8825-3o',  '8825_OE',  '324', 'R-3O'],
  // Farm
  FARM_SALES_LIVESTOCK:    ['F-1a',     'SF_SL',    '400', 'F-1A'],
  FARM_COST_LIVESTOCK:     ['F-1b',     'SF_CL',    '401', 'F-1B'],
  FARM_SALES_PRODUCTS:     ['F-2',      'SF_SP',    '402', 'F-2'],
  FARM_OTHER_INCOME:       ['F-3',      'SF_OI',    '403', 'F-3'],
  FARM_AG_PROGRAM_PMTS:    ['F-4a',     'SF_AP',    '404', 'F-4A'],
  FARM_CCC_LOANS:          ['F-5a',     'SF_CCC',   '405', 'F-5A'],
  FARM_CROP_INSURANCE:     ['F-6a',     'SF_CI',    '406', 'F-6A'],
  FARM_CUSTOM_HIRE_INC:    ['F-8',      'SF_CH',    '407', 'F-8'],
  FARM_CAR_TRUCK:          ['F-10',     'SF_CT',    '420', 'F-10'],
  FARM_CHEMICALS:          ['F-11',     'SF_CHM',   '421', 'F-11'],
  FARM_CONSERVATION:       ['F-12',     'SF_CON',   '422', 'F-12'],
  FARM_CUSTOM_HIRE_EXP:    ['F-13',     'SF_CHE',   '423', 'F-13'],
  FARM_DEPRECIATION:       ['F-14',     'SF_DEP',   '424', 'F-14'],
  FARM_EMPLOYEE_BENEFITS:  ['F-15',     'SF_EB',    '425', 'F-15'],
  FARM_FEED:               ['F-16',     'SF_FD',    '426', 'F-16'],
  FARM_FERTILIZER:         ['F-17',     'SF_FRT',   '427', 'F-17'],
  FARM_FREIGHT_TRUCKING:   ['F-18',     'SF_FT',    '428', 'F-18'],
  FARM_GASOLINE_FUEL:      ['F-19',     'SF_GF',    '429', 'F-19'],
  FARM_INSURANCE:          ['F-20',     'SF_INS',   '430', 'F-20'],
  FARM_MORTGAGE_INT:       ['F-21a',    'SF_MI',    '431', 'F-21A'],
  FARM_OTHER_INT:          ['F-21b',    'SF_OI',    '432', 'F-21B'],
  FARM_LABOR_HIRED:        ['F-22',     'SF_LH',    '433', 'F-22'],
  FARM_PENSION:            ['F-23',     'SF_PEN',   '434', 'F-23'],
  FARM_RENT_MACHINERY:     ['F-24a',    'SF_RM',    '435', 'F-24A'],
  FARM_RENT_LAND:          ['F-24b',    'SF_RL',    '436', 'F-24B'],
  FARM_REPAIRS:            ['F-25',     'SF_REP',   '437', 'F-25'],
  FARM_SEEDS_PLANTS:       ['F-26',     'SF_SP2',   '438', 'F-26'],
  FARM_STORAGE:            ['F-27',     'SF_STR',   '439', 'F-27'],
  FARM_SUPPLIES:           ['F-28',     'SF_SUP',   '440', 'F-28'],
  FARM_TAXES:              ['F-29',     'SF_TAX',   '441', 'F-29'],
  FARM_UTILITIES:          ['F-30',     'SF_UTL',   '442', 'F-30'],
  FARM_VETERINARY:         ['F-31',     'SF_VET',   '443', 'F-31'],
  FARM_OTHER_EXPENSES:     ['F-32',     'SF_OE',    '444', 'F-32'],
  // Farm Rental (Form 4835)
  FR_GROSS_FARM_RENTAL:    ['4835-1',   '4835_GR',  '500', 'FR-1'],
  FR_OTHER_INCOME:         ['4835-2',   '4835_OI',  '501', 'FR-2'],
  FR_CAR_TRUCK:            ['4835-3a',  '4835_CT',  '510', 'FR-3A'],
  FR_CHEMICALS:            ['4835-3b',  '4835_CHM', '511', 'FR-3B'],
  FR_CONSERVATION:         ['4835-3c',  '4835_CON', '512', 'FR-3C'],
  FR_CUSTOM_HIRE:          ['4835-3d',  '4835_CH',  '513', 'FR-3D'],
  FR_DEPRECIATION:         ['4835-3e',  '4835_DEP', '514', 'FR-3E'],
  FR_EMPLOYEE_BENEFITS:    ['4835-3f',  '4835_EB',  '515', 'FR-3F'],
  FR_FEED:                 ['4835-3g',  '4835_FD',  '516', 'FR-3G'],
  FR_FERTILIZER:           ['4835-3h',  '4835_FRT', '517', 'FR-3H'],
  FR_FREIGHT:              ['4835-3i',  '4835_FT',  '518', 'FR-3I'],
  FR_GASOLINE:             ['4835-3j',  '4835_GF',  '519', 'FR-3J'],
  FR_INSURANCE:            ['4835-3k',  '4835_INS', '520', 'FR-3K'],
  FR_MORTGAGE_INT:         ['4835-3l',  '4835_MI',  '521', 'FR-3L'],
  FR_OTHER_INT:            ['4835-3m',  '4835_OI2', '522', 'FR-3M'],
  FR_LABOR:                ['4835-3n',  '4835_LH',  '523', 'FR-3N'],
  FR_PENSION:              ['4835-3o',  '4835_PEN', '524', 'FR-3O'],
  FR_RENT_MACHINERY:       ['4835-3p',  '4835_RM',  '525', 'FR-3P'],
  FR_REPAIRS:              ['4835-3q',  '4835_REP', '526', 'FR-3Q'],
  FR_SEEDS:                ['4835-3r',  '4835_SDS', '527', 'FR-3R'],
  FR_STORAGE:              ['4835-3s',  '4835_STR', '528', 'FR-3S'],
  FR_SUPPLIES:             ['4835-3t',  '4835_SUP', '529', 'FR-3T'],
  FR_TAXES:                ['4835-3u',  '4835_TAX', '530', 'FR-3U'],
  FR_UTILITIES:            ['4835-3v',  '4835_UTL', '531', 'FR-3V'],
  FR_VETERINARY:           ['4835-3w',  '4835_VET', '532', 'FR-3W'],
  FR_OTHER_EXPENSES:       ['4835-3x',  '4835_OE',  '533', 'FR-3X'],
};

function getMaps(taxCode) {
  const sw = SW[taxCode];
  if (!sw) return [{ tax_software: 'generic', software_code: taxCode, software_description: null }];
  const [ut, cch, lac, gos] = sw;
  return [
    { tax_software: 'ultratax',  software_code: ut,     software_description: null },
    { tax_software: 'cch',       software_code: cch,    software_description: null },
    { tax_software: 'lacerte',   software_code: lac,    software_description: null },
    { tax_software: 'gosystem',  software_code: gos,    software_description: null },
    { tax_software: 'generic',   software_code: taxCode,software_description: null },
  ];
}

exports.seed = async function(knex) {
  const codes = [
    // ── 1065 BUSINESS ──────────────────────────────────────────────────────────
    // Page 1 Income
    { return_form:'1065', activity_type:'business', tax_code:'GROSS_RECEIPTS',          description:'Gross Receipts or Sales',                          sort_order:100, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'RETURNS_ALLOWANCES',       description:'Returns and Allowances',                           sort_order:101, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'COST_OF_GOODS_SOLD',       description:'Cost of Goods Sold (Schedule A)',                  sort_order:102, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'OTHER_INCOME',             description:'Other Income (Loss)',                              sort_order:107, is_system:true },
    // Page 1 Deductions
    { return_form:'1065', activity_type:'business', tax_code:'SALARIES_WAGES',           description:'Salaries and Wages (other than partners)',         sort_order:110, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'GUARANTEED_PAYMENTS',      description:'Guaranteed Payments to Partners',                  sort_order:111, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'REPAIRS_MAINTENANCE',      description:'Repairs and Maintenance',                          sort_order:112, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BAD_DEBTS',                description:'Bad Debts',                                        sort_order:113, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'RENT',                     description:'Rent',                                             sort_order:114, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'TAXES_LICENSES',           description:'Taxes and Licenses',                               sort_order:115, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'INTEREST_EXPENSE',         description:'Interest Expense',                                 sort_order:116, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'DEPRECIATION',             description:'Depreciation (not claimed on Sch K or elsewhere)', sort_order:117, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'DEPLETION',                description:'Depletion',                                        sort_order:118, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'RETIREMENT_PLANS',         description:'Retirement Plans, etc.',                           sort_order:119, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'EMPLOYEE_BENEFITS',        description:'Employee Benefit Programs',                        sort_order:120, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'OTHER_DEDUCTIONS',         description:'Other Deductions',                                 sort_order:121, is_system:true },
    // Schedule K
    { return_form:'1065', activity_type:'business', tax_code:'K1_INTEREST_INCOME',       description:'Schedule K — Interest Income',                     sort_order:150, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_ORDINARY_DIVIDENDS',    description:'Schedule K — Ordinary Dividends',                  sort_order:151, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_QUALIFIED_DIVIDENDS',   description:'Schedule K — Qualified Dividends',                 sort_order:152, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_ROYALTIES',             description:'Schedule K — Royalties',                           sort_order:153, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_NET_ST_CAP_GAIN_LOSS',  description:'Schedule K — Net Short-Term Capital Gain (Loss)',  sort_order:154, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_NET_LT_CAP_GAIN_LOSS',  description:'Schedule K — Net Long-Term Capital Gain (Loss)',   sort_order:155, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_UNRECAPTURED_SEC1250',  description:'Schedule K — Unrecaptured Section 1250 Gain',      sort_order:156, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_NET_SEC1231_GAIN_LOSS', description:'Schedule K — Net Section 1231 Gain (Loss)',        sort_order:157, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_OTHER_INCOME_LOSS',     description:'Schedule K — Other Income (Loss)',                 sort_order:158, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_SEC179_DEDUCTION',      description:'Schedule K — Section 179 Deduction',              sort_order:159, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_OTHER_DEDUCTIONS',      description:'Schedule K — Other Deductions',                    sort_order:160, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_CHARITABLE_CONTRIB',    description:'Schedule K — Charitable Contributions',            sort_order:161, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_INVESTMENT_INT_EXP',    description:'Schedule K — Investment Interest Expense',         sort_order:162, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_FOREIGN_TAX_CREDIT',    description:'Schedule K — Foreign Tax Credit',                  sort_order:163, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_AMT_ITEMS',             description:'Schedule K — Alternative Minimum Tax Items',       sort_order:164, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_TAX_EXEMPT_INT',        description:'Schedule K — Tax-Exempt Interest Income',          sort_order:165, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_NONDEDUCTIBLE_EXP',     description:'Schedule K — Nondeductible Expenses',              sort_order:166, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'K1_DISTRIBUTIONS',         description:'Schedule K — Distributions',                       sort_order:167, is_system:true },
    // Schedule L — Assets
    { return_form:'1065', activity_type:'business', tax_code:'BS_CASH',                  description:'Schedule L — Cash',                                sort_order:200, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_TRADE_NOTES_AR',        description:'Schedule L — Trade Notes and Accounts Receivable',  sort_order:201, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_ALLOWANCE_BAD_DEBTS',   description:'Schedule L — Less Allowance for Bad Debts',         sort_order:202, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_INVENTORIES',           description:'Schedule L — Inventories',                         sort_order:203, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_US_GOVT_OBLIGATIONS',   description:'Schedule L — U.S. Government Obligations',          sort_order:204, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_TAX_EXEMPT_SECURITIES', description:'Schedule L — Tax-Exempt Securities',               sort_order:205, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_OTHER_CURRENT_ASSETS',  description:'Schedule L — Other Current Assets',                sort_order:206, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_LOANS_TO_PARTNERS',     description:'Schedule L — Loans to Partners (or Persons Related)',sort_order:207, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_MORTGAGE_RE_LOANS',     description:'Schedule L — Mortgage and Real Estate Loans',       sort_order:208, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_OTHER_INVESTMENTS',     description:'Schedule L — Other Investments',                    sort_order:209, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_BUILDINGS_LAND',        description:'Schedule L — Buildings and Other Depreciable Assets',sort_order:210, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_ACCUM_DEPRECIATION',    description:'Schedule L — Less Accumulated Depreciation',        sort_order:211, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_DEPLETABLE_ASSETS',     description:'Schedule L — Depletable Assets',                   sort_order:212, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_ACCUM_DEPLETION',       description:'Schedule L — Less Accumulated Depletion',           sort_order:213, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_LAND',                  description:'Schedule L — Land (net of any amortization)',       sort_order:214, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_INTANGIBLE_ASSETS',     description:'Schedule L — Intangible Assets (amortizable only)', sort_order:215, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_ACCUM_AMORTIZATION',    description:'Schedule L — Less Accumulated Amortization',        sort_order:216, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_OTHER_ASSETS',          description:'Schedule L — Other Assets',                         sort_order:217, is_system:true },
    // Schedule L — Liabilities & Capital
    { return_form:'1065', activity_type:'business', tax_code:'BS_ACCOUNTS_PAYABLE',      description:'Schedule L — Accounts Payable',                    sort_order:220, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_NOTES_PAYABLE_LT1YR',   description:'Schedule L — Mortgages/Notes/Bonds Payable < 1 Year',sort_order:221, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_OTHER_CURRENT_LIAB',    description:'Schedule L — Other Current Liabilities',            sort_order:222, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_LOANS_FROM_PARTNERS',   description:'Schedule L — Loans from Partners (or Persons Related)',sort_order:223, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_MORTGAGES_GT1YR',       description:'Schedule L — Mortgages/Notes/Bonds Payable ≥ 1 Year',sort_order:224, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_OTHER_LIABILITIES',     description:'Schedule L — Other Liabilities',                    sort_order:225, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'BS_PARTNER_CAPITAL',       description:'Schedule L — Partners\' Capital Accounts',          sort_order:226, is_system:true },
    // Schedule M-1
    { return_form:'1065', activity_type:'business', tax_code:'M1_NET_INCOME_BOOKS',      description:'Schedule M-1 — Net Income (Loss) per Books',        sort_order:250, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M1_INCOME_RTN_NOT_BOOKS',  description:'Schedule M-1 — Income on Return Not on Books',       sort_order:251, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M1_GUARANTEED_PMTS_M1',    description:'Schedule M-1 — Guaranteed Payments',                sort_order:252, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M1_EXP_BOOKS_NOT_RTN',     description:'Schedule M-1 — Expenses on Books Not on Return',     sort_order:253, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M1_INC_BOOKS_NOT_RTN',     description:'Schedule M-1 — Income on Books Not on Return',       sort_order:254, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M1_DED_RTN_NOT_BOOKS',     description:'Schedule M-1 — Deductions on Return Not on Books',   sort_order:255, is_system:true },
    // Schedule M-2
    { return_form:'1065', activity_type:'business', tax_code:'M2_BEGINNING_CAPITAL',     description:'Schedule M-2 — Balance at Beginning of Year',        sort_order:260, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M2_CAPITAL_CONTRIBUTED',   description:'Schedule M-2 — Capital Contributed During Year',     sort_order:261, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M2_NET_INCOME_M2',         description:'Schedule M-2 — Net Income per Books',                sort_order:262, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M2_OTHER_INCREASES',       description:'Schedule M-2 — Other Increases',                     sort_order:263, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M2_DISTRIBUTIONS_CASH',    description:'Schedule M-2 — Distributions: Cash',                 sort_order:264, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M2_DISTRIBUTIONS_PROP',    description:'Schedule M-2 — Distributions: Property',             sort_order:265, is_system:true },
    { return_form:'1065', activity_type:'business', tax_code:'M2_OTHER_DECREASES',       description:'Schedule M-2 — Other Decreases',                     sort_order:266, is_system:true },

    // ── 1065 RENTAL (Form 8825) ─────────────────────────────────────────────
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_GROSS_RENTS',       description:'Form 8825 — Gross Rents',                  sort_order:300, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_OTHER_INCOME',      description:'Form 8825 — Other Income',                 sort_order:301, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_ADVERTISING',       description:'Form 8825 — Advertising',                  sort_order:310, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_AUTO_TRAVEL',       description:'Form 8825 — Auto and Travel',              sort_order:311, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_CLEANING_MAINT',    description:'Form 8825 — Cleaning and Maintenance',     sort_order:312, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_COMMISSIONS',       description:'Form 8825 — Commissions',                  sort_order:313, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_INSURANCE',         description:'Form 8825 — Insurance',                    sort_order:314, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_LEGAL_PROF',        description:'Form 8825 — Legal and Professional Fees',  sort_order:315, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_MGMT_FEES',         description:'Form 8825 — Management Fees',              sort_order:316, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_MORTGAGE_INT',      description:'Form 8825 — Mortgage Interest',            sort_order:317, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_OTHER_INT',         description:'Form 8825 — Other Interest',               sort_order:318, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_REPAIRS',           description:'Form 8825 — Repairs',                      sort_order:319, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_SUPPLIES',          description:'Form 8825 — Supplies',                     sort_order:320, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_TAXES',             description:'Form 8825 — Taxes',                        sort_order:321, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_UTILITIES',         description:'Form 8825 — Utilities',                    sort_order:322, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_DEPRECIATION',      description:'Form 8825 — Depreciation',                 sort_order:323, is_system:true },
    { return_form:'1065', activity_type:'rental', tax_code:'RENTAL_OTHER_EXPENSES',    description:'Form 8825 — Other Expenses',               sort_order:324, is_system:true },

    // ── 1065 FARM ───────────────────────────────────────────────────────────
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_SALES_LIVESTOCK',     description:'Farm Income — Sales of Livestock and Other Items',  sort_order:400, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_COST_LIVESTOCK',      description:'Farm Income — Cost or Basis of Livestock Sold',     sort_order:401, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_SALES_PRODUCTS',      description:'Farm Income — Sales of Products You Raised',        sort_order:402, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_OTHER_INCOME',        description:'Farm Income — Other Farm Income',                   sort_order:403, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_AG_PROGRAM_PMTS',     description:'Farm Income — Agricultural Program Payments',       sort_order:404, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_CCC_LOANS',           description:'Farm Income — CCC Loans Reported Under Election',   sort_order:405, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_CROP_INSURANCE',      description:'Farm Income — Crop Insurance Proceeds',             sort_order:406, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_CUSTOM_HIRE_INC',     description:'Farm Income — Custom Hire (Machine Work) Income',   sort_order:407, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_CAR_TRUCK',           description:'Farm Expense — Car and Truck Expenses',             sort_order:420, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_CHEMICALS',           description:'Farm Expense — Chemicals',                          sort_order:421, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_CONSERVATION',        description:'Farm Expense — Conservation Expenses',              sort_order:422, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_CUSTOM_HIRE_EXP',     description:'Farm Expense — Custom Hire (Machine Work)',         sort_order:423, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_DEPRECIATION',        description:'Farm Expense — Depreciation and Section 179',       sort_order:424, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_EMPLOYEE_BENEFITS',   description:'Farm Expense — Employee Benefit Programs',          sort_order:425, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_FEED',                description:'Farm Expense — Feed',                               sort_order:426, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_FERTILIZER',          description:'Farm Expense — Fertilizers and Lime',               sort_order:427, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_FREIGHT_TRUCKING',    description:'Farm Expense — Freight and Trucking',               sort_order:428, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_GASOLINE_FUEL',       description:'Farm Expense — Gasoline, Fuel, and Oil',            sort_order:429, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_INSURANCE',           description:'Farm Expense — Insurance (other than health)',      sort_order:430, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_MORTGAGE_INT',        description:'Farm Expense — Mortgage Interest',                  sort_order:431, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_OTHER_INT',           description:'Farm Expense — Other Interest',                     sort_order:432, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_LABOR_HIRED',         description:'Farm Expense — Labor Hired',                        sort_order:433, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_PENSION',             description:'Farm Expense — Pension and Profit-Sharing Plans',   sort_order:434, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_RENT_MACHINERY',      description:'Farm Expense — Rent/Lease — Vehicles, Machinery',   sort_order:435, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_RENT_LAND',           description:'Farm Expense — Rent/Lease — Other (Land, Animals)', sort_order:436, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_REPAIRS',             description:'Farm Expense — Repairs and Maintenance',            sort_order:437, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_SEEDS_PLANTS',        description:'Farm Expense — Seeds and Plants',                   sort_order:438, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_STORAGE',             description:'Farm Expense — Storage and Warehousing',            sort_order:439, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_SUPPLIES',            description:'Farm Expense — Supplies',                           sort_order:440, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_TAXES',               description:'Farm Expense — Taxes',                              sort_order:441, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_UTILITIES',           description:'Farm Expense — Utilities',                          sort_order:442, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_VETERINARY',          description:'Farm Expense — Veterinary, Breeding, and Medicine',  sort_order:443, is_system:true },
    { return_form:'1065', activity_type:'farm', tax_code:'FARM_OTHER_EXPENSES',      description:'Farm Expense — Other Expenses',                     sort_order:444, is_system:true },

    // ── 1065 FARM RENTAL (Form 4835) ─────────────────────────────────────────
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_GROSS_FARM_RENTAL', description:'Form 4835 — Gross Farm Rental Income',                sort_order:500, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_OTHER_INCOME',      description:'Form 4835 — Other Income',                            sort_order:501, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_CAR_TRUCK',         description:'Form 4835 — Car and Truck Expenses',                  sort_order:510, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_CHEMICALS',         description:'Form 4835 — Chemicals',                               sort_order:511, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_CONSERVATION',      description:'Form 4835 — Conservation Expenses',                   sort_order:512, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_CUSTOM_HIRE',       description:'Form 4835 — Custom Hire',                             sort_order:513, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_DEPRECIATION',      description:'Form 4835 — Depreciation',                            sort_order:514, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_EMPLOYEE_BENEFITS', description:'Form 4835 — Employee Benefit Programs',               sort_order:515, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_FEED',              description:'Form 4835 — Feed',                                    sort_order:516, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_FERTILIZER',        description:'Form 4835 — Fertilizers and Lime',                    sort_order:517, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_FREIGHT',           description:'Form 4835 — Freight and Trucking',                    sort_order:518, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_GASOLINE',          description:'Form 4835 — Gasoline, Fuel, and Oil',                 sort_order:519, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_INSURANCE',         description:'Form 4835 — Insurance',                               sort_order:520, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_MORTGAGE_INT',      description:'Form 4835 — Mortgage Interest',                       sort_order:521, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_OTHER_INT',         description:'Form 4835 — Other Interest',                          sort_order:522, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_LABOR',             description:'Form 4835 — Labor Hired',                             sort_order:523, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_PENSION',           description:'Form 4835 — Pension and Profit-Sharing Plans',        sort_order:524, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_RENT_MACHINERY',    description:'Form 4835 — Rent/Lease — Vehicles, Machinery',        sort_order:525, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_REPAIRS',           description:'Form 4835 — Repairs and Maintenance',                 sort_order:526, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_SEEDS',             description:'Form 4835 — Seeds and Plants',                        sort_order:527, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_STORAGE',           description:'Form 4835 — Storage and Warehousing',                 sort_order:528, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_SUPPLIES',          description:'Form 4835 — Supplies',                                sort_order:529, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_TAXES',             description:'Form 4835 — Taxes',                                   sort_order:530, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_UTILITIES',         description:'Form 4835 — Utilities',                               sort_order:531, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_VETERINARY',        description:'Form 4835 — Veterinary, Breeding, and Medicine',       sort_order:532, is_system:true },
    { return_form:'1065', activity_type:'farm_rental', tax_code:'FR_OTHER_EXPENSES',    description:'Form 4835 — Other Expenses',                          sort_order:533, is_system:true },
  ];

  for (const code of codes) {
    const [row] = await knex('tax_codes')
      .insert({ ...code, created_at: knex.fn.now(), updated_at: knex.fn.now() })
      .onConflict(['return_form', 'activity_type', 'tax_code'])
      .merge(['description', 'sort_order', 'is_system', 'updated_at'])
      .returning('id');
    const maps = getMaps(code.tax_code);
    for (const map of maps) {
      await knex('tax_code_software_maps')
        .insert({ tax_code_id: row.id, ...map, created_at: knex.fn.now() })
        .onConflict(['tax_code_id', 'tax_software'])
        .merge(['software_code', 'software_description']);
    }
  }
};
