exports.seed = async function(knex) {
  const codes = [
    // ─── 1120S business (Page 1 Income) sort 3000-3099 ───────────────────────
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_GROSS_RECEIPTS',           description: 'Gross receipts or sales',                         sort_order: 3000, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_RETURNS_ALLOWANCES',        description: 'Returns and allowances',                          sort_order: 3005, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_COST_OF_GOODS_SOLD',        description: 'Cost of goods sold',                              sort_order: 3010, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_GROSS_PROFIT',              description: 'Gross profit',                                    sort_order: 3015, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_NET_GAIN_4797',             description: 'Net gain (loss) from Form 4797',                  sort_order: 3020, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_OTHER_INCOME',              description: 'Other income (loss)',                             sort_order: 3025, is_system: true },

    // ─── 1120S business (Page 1 Deductions) sort 3100-3199 ───────────────────
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_COMPENSATION_OFFICERS',    description: 'Compensation of officers',                        sort_order: 3100, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_SALARIES_WAGES',           description: 'Salaries and wages',                              sort_order: 3105, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_REPAIRS_MAINTENANCE',      description: 'Repairs and maintenance',                         sort_order: 3110, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BAD_DEBTS',                description: 'Bad debts',                                       sort_order: 3115, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_RENTS',                    description: 'Rents',                                           sort_order: 3120, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_TAXES_LICENSES',           description: 'Taxes and licenses',                              sort_order: 3125, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_INTEREST_EXP',             description: 'Interest expense',                                sort_order: 3130, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_DEPRECIATION',             description: 'Depreciation not claimed on Schedule A or elsewhere', sort_order: 3135, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_DEPLETION',                description: 'Depletion',                                       sort_order: 3140, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_ADVERTISING',              description: 'Advertising',                                     sort_order: 3145, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_PENSION_PROFIT_SHARING',   description: 'Pension, profit-sharing, etc. plans',             sort_order: 3150, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_EMPLOYEE_BENEFITS',        description: 'Employee benefit programs',                       sort_order: 3155, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_OTHER_DEDUCTIONS',         description: 'Other deductions',                                sort_order: 3160, is_system: true },

    // ─── 1120S Schedule K items sort 3200-3299 ───────────────────────────────
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_INTEREST_INCOME',       description: 'Interest income (Schedule K)',                    sort_order: 3200, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_ORDINARY_DIVIDENDS',    description: 'Ordinary dividends (Schedule K)',                 sort_order: 3205, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_QUALIFIED_DIVIDENDS',   description: 'Qualified dividends (Schedule K)',                sort_order: 3210, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_ROYALTIES',             description: 'Royalties (Schedule K)',                          sort_order: 3215, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_NET_ST_CAP_GAIN_LOSS',  description: 'Net short-term capital gain (loss) (Schedule K)', sort_order: 3220, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_NET_LT_CAP_GAIN_LOSS',  description: 'Net long-term capital gain (loss) (Schedule K)',  sort_order: 3225, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_UNRECAPTURED_1250',     description: 'Unrecaptured Section 1250 gain (Schedule K)',     sort_order: 3230, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_NET_1231_GAIN_LOSS',    description: 'Net Section 1231 gain (loss) (Schedule K)',       sort_order: 3235, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_OTHER_INCOME_LOSS',     description: 'Other income (loss) (Schedule K)',                sort_order: 3240, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_SEC179_DEDUCTION',      description: 'Section 179 deduction (Schedule K)',              sort_order: 3245, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_CHARITABLE_CONTRIBUTIONS', description: 'Charitable contributions (Schedule K)',        sort_order: 3250, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_INVESTMENT_INTEREST',   description: 'Investment interest expense (Schedule K)',        sort_order: 3255, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_FOREIGN_TAX_CREDIT',    description: 'Foreign tax credit (Schedule K)',                 sort_order: 3260, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_AMT_ITEMS',             description: 'AMT items (Schedule K)',                          sort_order: 3265, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_K1_OTHER_DEDUCTIONS',      description: 'Other deductions (Schedule K)',                   sort_order: 3270, is_system: true },

    // ─── 1120S Schedule L Balance Sheet sort 3300-3499 ───────────────────────
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_CASH',                       description: 'Cash',                                          sort_order: 3300, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_TRADE_NOTES_AR',             description: 'Trade notes and accounts receivable',           sort_order: 3305, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_INVENTORIES',                description: 'Inventories',                                   sort_order: 3310, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_US_GOVT_OBLIGATIONS',        description: 'U.S. government obligations',                   sort_order: 3315, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_TAX_EXEMPT_SECURITIES',      description: 'Tax-exempt securities',                         sort_order: 3320, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_OTHER_CURRENT_ASSETS',       description: 'Other current assets',                          sort_order: 3325, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_LOANS_TO_SHAREHOLDERS',      description: 'Loans to shareholders',                         sort_order: 3330, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_MORTGAGE_REAL_ESTATE',       description: 'Mortgage and real estate loans',                sort_order: 3335, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_OTHER_INVESTMENTS',          description: 'Other investments',                             sort_order: 3340, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_BUILDINGS_LAND',             description: 'Buildings and other depreciable assets',        sort_order: 3345, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_ACCUMULATED_DEPRECIATION',   description: 'Less accumulated depreciation',                 sort_order: 3350, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_LAND',                       description: 'Land (net of any amortization)',                sort_order: 3355, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_INTANGIBLE_ASSETS',          description: 'Intangible assets (amortizable only)',          sort_order: 3360, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_ACCUMULATED_AMORTIZATION',   description: 'Less accumulated amortization',                 sort_order: 3365, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_OTHER_ASSETS',               description: 'Other assets',                                  sort_order: 3370, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_ACCOUNTS_PAYABLE',           description: 'Accounts payable',                              sort_order: 3375, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_NOTES_PAYABLE_LT1YR',        description: 'Mortgages, notes, bonds payable in less than 1 year', sort_order: 3380, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_OTHER_CURRENT_LIABILITIES',  description: 'Other current liabilities',                     sort_order: 3385, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_LOANS_FROM_SHAREHOLDERS',    description: 'Loans from shareholders',                       sort_order: 3390, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_MORTGAGES_GT1YR',            description: 'Mortgages, notes, bonds payable in 1 year or more', sort_order: 3395, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_OTHER_LIABILITIES',          description: 'Other liabilities',                             sort_order: 3400, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_CAPITAL_STOCK',              description: 'Capital stock',                                 sort_order: 3405, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_ADDITIONAL_PAID_IN_CAPITAL', description: 'Additional paid-in capital',                    sort_order: 3410, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_AAA',                        description: 'Accumulated adjustments account (AAA)',         sort_order: 3415, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_OAA',                        description: 'Other adjustments account (OAA)',               sort_order: 3420, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_RETAINED_EARNINGS_PTI',      description: 'Retained earnings — previously taxed income',   sort_order: 3425, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_BS_LESS_TREASURY_STOCK',        description: 'Less cost of treasury stock',                   sort_order: 3430, is_system: true },

    // ─── 1120S M-1 sort 3500-3549 ────────────────────────────────────────────
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M1_NET_INCOME_PER_BOOKS',           description: 'Net income (loss) per books',                            sort_order: 3500, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M1_INCOME_RETURN_NOT_BOOKS',        description: 'Income included on return not recorded on books',        sort_order: 3505, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M1_EXPENSES_BOOKS_NOT_RETURN',      description: 'Expenses recorded on books not included on return',      sort_order: 3510, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M1_INCOME_BOOKS_NOT_RETURN',        description: 'Income recorded on books not included on return',        sort_order: 3515, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M1_DEDUCTIONS_RETURN_NOT_BOOKS',    description: 'Deductions on return not charged against book income',   sort_order: 3520, is_system: true },

    // ─── 1120S M-2 AAA/OAA sort 3550-3599 ────────────────────────────────────
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M2_AAA_BEGINNING',         description: 'AAA — balance at beginning of year',             sort_order: 3550, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M2_AAA_ORDINARY_INCOME',   description: 'AAA — ordinary income from page 1',              sort_order: 3555, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M2_AAA_OTHER_ADDITIONS',   description: 'AAA — other additions',                          sort_order: 3560, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M2_AAA_LOSSES_DEDUCTIONS', description: 'AAA — loss and deductions',                      sort_order: 3565, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M2_AAA_OTHER_REDUCTIONS',  description: 'AAA — other reductions',                         sort_order: 3570, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M2_AAA_DISTRIBUTIONS',     description: 'AAA — distributions',                           sort_order: 3575, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M2_OAA_BEGINNING',         description: 'OAA — balance at beginning of year',             sort_order: 3580, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M2_OAA_INCREASES',         description: 'OAA — increases',                               sort_order: 3585, is_system: true },
    { return_form: '1120S', activity_type: 'business', tax_code: 'S_M2_OAA_DECREASES',         description: 'OAA — decreases',                               sort_order: 3590, is_system: true },

    // ─── 1120S rental (mirrors 1065 rental RENTAL_*) sort 3600-3699 ──────────
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_GROSS_RENTS',           description: 'Gross rents',                                     sort_order: 3600, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_OTHER_INCOME',          description: 'Other rental income',                             sort_order: 3605, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_ADVERTISING',           description: 'Advertising',                                     sort_order: 3610, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_AUTO_TRAVEL',           description: 'Auto and travel',                                 sort_order: 3615, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_CLEANING_MAINTENANCE',  description: 'Cleaning and maintenance',                        sort_order: 3620, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_COMMISSIONS',           description: 'Commissions',                                     sort_order: 3625, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_INSURANCE',             description: 'Insurance',                                       sort_order: 3630, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_LEGAL_PROFESSIONAL',    description: 'Legal and professional fees',                     sort_order: 3635, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_MANAGEMENT_FEES',       description: 'Management fees',                                 sort_order: 3640, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_MORTGAGE_INTEREST',     description: 'Mortgage interest paid to banks, etc.',           sort_order: 3645, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_OTHER_INTEREST',        description: 'Other interest',                                  sort_order: 3650, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_REPAIRS',               description: 'Repairs',                                         sort_order: 3655, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_SUPPLIES',              description: 'Supplies',                                        sort_order: 3660, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_TAXES',                 description: 'Taxes',                                           sort_order: 3665, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_UTILITIES',             description: 'Utilities',                                       sort_order: 3670, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_DEPRECIATION',          description: 'Depreciation expense or depletion',               sort_order: 3675, is_system: true },
    { return_form: '1120S', activity_type: 'rental', tax_code: 'RENTAL_OTHER_EXPENSES',        description: 'Other expenses',                                  sort_order: 3680, is_system: true },

    // ─── 1120S farm (mirrors 1065 farm FARM_*) sort 3700-3799 ────────────────
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_SALES_LIVESTOCK_PRODUCTS',  description: 'Sales of livestock and other items bought for resale', sort_order: 3700, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_COST_BASIS_LIVESTOCK',      description: 'Cost or other basis of livestock and items',      sort_order: 3705, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_OTHER_FARM_INCOME',         description: 'Other farm income',                               sort_order: 3710, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_AG_PROGRAM_PAYMENTS',       description: 'Agricultural program payments',                   sort_order: 3715, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_CCC_LOANS',                 description: 'CCC loans reported under election',               sort_order: 3720, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_CROP_INSURANCE',            description: 'Crop insurance proceeds and federal crop disaster payments', sort_order: 3725, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_CUSTOM_HIRE_INCOME',        description: 'Custom hire (machine work) income',               sort_order: 3730, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_CAR_TRUCK',                 description: 'Car and truck expenses',                          sort_order: 3735, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_CHEMICALS',                 description: 'Chemicals',                                       sort_order: 3740, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_CONSERVATION',              description: 'Conservation expenses',                           sort_order: 3745, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_CUSTOM_HIRE_EXP',           description: 'Custom hire (machine work) expense',              sort_order: 3750, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_DEPRECIATION',              description: 'Depreciation and Section 179',                    sort_order: 3755, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_EMPLOYEE_BENEFITS',         description: 'Employee benefit programs',                       sort_order: 3760, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_FEED',                      description: 'Feed',                                            sort_order: 3765, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_FERTILIZER',                description: 'Fertilizers and lime',                            sort_order: 3770, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_FREIGHT_TRUCKING',          description: 'Freight and trucking',                            sort_order: 3775, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_GASOLINE_FUEL',             description: 'Gasoline, fuel, and oil',                         sort_order: 3780, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_INSURANCE',                 description: 'Insurance (other than health)',                   sort_order: 3785, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_MORTGAGE_INTEREST',         description: 'Mortgage interest',                               sort_order: 3790, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_OTHER_INTEREST',            description: 'Other interest',                                  sort_order: 3795, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_LABOR_HIRED',               description: 'Labor hired',                                     sort_order: 3800, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_PENSION',                   description: 'Pension and profit-sharing plans',                sort_order: 3805, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_RENT_MACHINERY',            description: 'Rent or lease — vehicles, machinery, equipment',  sort_order: 3810, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_RENT_LAND',                 description: 'Rent or lease — land, animals',                   sort_order: 3815, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_REPAIRS',                   description: 'Repairs and maintenance',                         sort_order: 3820, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_SEEDS_PLANTS',              description: 'Seeds and plants',                                sort_order: 3825, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_STORAGE',                   description: 'Storage and warehousing',                         sort_order: 3830, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_SUPPLIES',                  description: 'Supplies',                                        sort_order: 3835, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_TAXES',                     description: 'Taxes',                                           sort_order: 3840, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_UTILITIES',                 description: 'Utilities',                                       sort_order: 3845, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_VETERINARY',                description: 'Veterinary, breeding, and medicine',              sort_order: 3850, is_system: true },
    { return_form: '1120S', activity_type: 'farm', tax_code: 'FARM_OTHER_EXPENSES',            description: 'Other farm expenses',                             sort_order: 3855, is_system: true },

    // ─── 1120S farm_rental (mirrors 1065 farm_rental FR_*) sort 3860-3899 ────
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_GROSS_FARM_RENTAL',    description: 'Gross farm rental income',                        sort_order: 3860, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_OTHER_INCOME',         description: 'Other income',                                    sort_order: 3862, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_CAR_TRUCK',            description: 'Car and truck expenses',                          sort_order: 3865, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_CHEMICALS',            description: 'Chemicals',                                       sort_order: 3867, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_CONSERVATION',         description: 'Conservation expenses',                           sort_order: 3869, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_CUSTOM_HIRE',          description: 'Custom hire (machine work)',                       sort_order: 3871, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_DEPRECIATION',         description: 'Depreciation and Section 179',                    sort_order: 3873, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_EMPLOYEE_BENEFITS',    description: 'Employee benefit programs',                       sort_order: 3875, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_FEED',                 description: 'Feed',                                            sort_order: 3877, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_FERTILIZER',           description: 'Fertilizers and lime',                            sort_order: 3879, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_FREIGHT',              description: 'Freight and trucking',                            sort_order: 3881, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_GASOLINE',             description: 'Gasoline, fuel, and oil',                         sort_order: 3883, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_INSURANCE',            description: 'Insurance',                                       sort_order: 3885, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_MORTGAGE_INTEREST',    description: 'Mortgage interest',                               sort_order: 3887, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_OTHER_INTEREST',       description: 'Other interest',                                  sort_order: 3889, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_LABOR',                description: 'Labor hired',                                     sort_order: 3891, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_PENSION',              description: 'Pension and profit-sharing plans',                sort_order: 3893, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_RENT_MACHINERY',       description: 'Rent or lease — machinery and equipment',         sort_order: 3895, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_REPAIRS',              description: 'Repairs and maintenance',                         sort_order: 3897, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_SEEDS',                description: 'Seeds and plants',                                sort_order: 3899, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_STORAGE',              description: 'Storage and warehousing',                         sort_order: 3901, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_SUPPLIES',             description: 'Supplies',                                        sort_order: 3903, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_TAXES',                description: 'Taxes',                                           sort_order: 3905, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_UTILITIES',            description: 'Utilities',                                       sort_order: 3907, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_VETERINARY',           description: 'Veterinary, breeding, and medicine',              sort_order: 3909, is_system: true },
    { return_form: '1120S', activity_type: 'farm_rental', tax_code: 'FR_OTHER_EXPENSES',       description: 'Other farm rental expenses',                      sort_order: 3911, is_system: true },

    // ─── 1040 Schedule C Income sort 4000-4049 ───────────────────────────────
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_GROSS_RECEIPTS',           description: 'Gross receipts or sales',                         sort_order: 4000, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_RETURNS_ALLOWANCES',       description: 'Returns and allowances',                          sort_order: 4005, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_COST_OF_GOODS_SOLD',       description: 'Cost of goods sold',                              sort_order: 4010, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_OTHER_INCOME',             description: 'Other income',                                    sort_order: 4015, is_system: true },

    // ─── 1040 Schedule C Expenses (Part II) sort 4050-4199 ───────────────────
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_ADVERTISING',              description: 'Advertising',                                     sort_order: 4050, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_CAR_TRUCK',                description: 'Car and truck expenses',                          sort_order: 4055, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_COMMISSIONS_FEES',         description: 'Commissions and fees',                            sort_order: 4060, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_CONTRACT_LABOR',           description: 'Contract labor',                                  sort_order: 4065, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_DEPLETION',                description: 'Depletion',                                       sort_order: 4070, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_DEPRECIATION',             description: 'Depreciation and Section 179',                    sort_order: 4075, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_EMPLOYEE_BENEFITS',        description: 'Employee benefit programs',                       sort_order: 4080, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_INSURANCE',                description: 'Insurance (other than health)',                   sort_order: 4085, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_MORTGAGE_INTEREST',        description: 'Mortgage interest',                               sort_order: 4090, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_OTHER_INTEREST',           description: 'Other interest',                                  sort_order: 4095, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_LEGAL_PROFESSIONAL',       description: 'Legal and professional services',                 sort_order: 4100, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_OFFICE_EXPENSE',           description: 'Office expense',                                  sort_order: 4105, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_PENSION_PROFIT_SHARING',   description: 'Pension and profit-sharing plans',                sort_order: 4110, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_RENT_LEASE_VEHICLES',      description: 'Rent or lease — vehicles, machinery, equipment',  sort_order: 4115, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_RENT_LEASE_OTHER',         description: 'Rent or lease — other business property',         sort_order: 4120, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_REPAIRS_MAINTENANCE',      description: 'Repairs and maintenance',                         sort_order: 4125, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_SUPPLIES',                 description: 'Supplies',                                        sort_order: 4130, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_TAXES_LICENSES',           description: 'Taxes and licenses',                              sort_order: 4135, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_TRAVEL',                   description: 'Travel',                                          sort_order: 4140, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_MEALS_50PCT',              description: 'Meals (50%)',                                     sort_order: 4145, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_UTILITIES',                description: 'Utilities',                                       sort_order: 4150, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_WAGES',                    description: 'Wages',                                           sort_order: 4155, is_system: true },
    { return_form: '1040', activity_type: 'business', tax_code: 'SC_OTHER_EXPENSES',           description: 'Other expenses',                                  sort_order: 4160, is_system: true },

    // ─── 1040 Schedule E rental sort 4300-4499 ───────────────────────────────
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_RENTS_RECEIVED',             description: 'Rents received',                                  sort_order: 4300, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_ROYALTIES_RECEIVED',         description: 'Royalties received',                              sort_order: 4305, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_ADVERTISING',                description: 'Advertising',                                     sort_order: 4310, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_AUTO_TRAVEL',                description: 'Auto and travel',                                 sort_order: 4315, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_CLEANING_MAINTENANCE',       description: 'Cleaning and maintenance',                        sort_order: 4320, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_COMMISSIONS',                description: 'Commissions',                                     sort_order: 4325, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_INSURANCE',                  description: 'Insurance',                                       sort_order: 4330, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_LEGAL_PROFESSIONAL',         description: 'Legal and professional fees',                     sort_order: 4335, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_MANAGEMENT_FEES',            description: 'Management fees',                                 sort_order: 4340, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_MORTGAGE_INTEREST',          description: 'Mortgage interest paid to banks, etc.',           sort_order: 4345, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_OTHER_INTEREST',             description: 'Other interest',                                  sort_order: 4350, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_REPAIRS',                    description: 'Repairs',                                         sort_order: 4355, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_SUPPLIES',                   description: 'Supplies',                                        sort_order: 4360, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_TAXES',                      description: 'Taxes',                                           sort_order: 4365, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_UTILITIES',                  description: 'Utilities',                                       sort_order: 4370, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_DEPRECIATION',               description: 'Depreciation expense or depletion',               sort_order: 4375, is_system: true },
    { return_form: '1040', activity_type: 'rental', tax_code: 'SE_OTHER_EXPENSES',             description: 'Other expenses',                                  sort_order: 4380, is_system: true },

    // ─── 1040 Schedule F farm sort 4500-4699 ─────────────────────────────────
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_SALES_LIVESTOCK_PRODUCTS',     description: 'Sales of livestock and other items bought for resale', sort_order: 4500, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_COST_BASIS_LIVESTOCK',         description: 'Cost or other basis of livestock and items',      sort_order: 4505, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_OTHER_FARM_INCOME',            description: 'Other farm income',                               sort_order: 4510, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_AG_PROGRAM_PAYMENTS',          description: 'Agricultural program payments',                   sort_order: 4515, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_CCC_LOANS',                    description: 'CCC loans reported under election',               sort_order: 4520, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_CROP_INSURANCE',               description: 'Crop insurance proceeds and federal crop disaster payments', sort_order: 4525, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_CUSTOM_HIRE_INCOME',           description: 'Custom hire (machine work) income',               sort_order: 4530, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_CAR_TRUCK',                    description: 'Car and truck expenses',                          sort_order: 4535, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_CHEMICALS',                    description: 'Chemicals',                                       sort_order: 4540, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_CONSERVATION',                 description: 'Conservation expenses',                           sort_order: 4545, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_CUSTOM_HIRE_EXP',              description: 'Custom hire (machine work) expense',              sort_order: 4550, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_DEPRECIATION',                 description: 'Depreciation and Section 179',                    sort_order: 4555, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_EMPLOYEE_BENEFITS',            description: 'Employee benefit programs',                       sort_order: 4560, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_FEED',                         description: 'Feed',                                            sort_order: 4565, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_FERTILIZER',                   description: 'Fertilizers and lime',                            sort_order: 4570, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_FREIGHT_TRUCKING',             description: 'Freight and trucking',                            sort_order: 4575, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_GASOLINE_FUEL',                description: 'Gasoline, fuel, and oil',                         sort_order: 4580, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_INSURANCE',                    description: 'Insurance (other than health)',                   sort_order: 4585, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_MORTGAGE_INTEREST',            description: 'Mortgage interest',                               sort_order: 4590, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_OTHER_INTEREST',               description: 'Other interest',                                  sort_order: 4595, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_LABOR_HIRED',                  description: 'Labor hired',                                     sort_order: 4600, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_PENSION',                      description: 'Pension and profit-sharing plans',                sort_order: 4605, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_RENT_MACHINERY',               description: 'Rent or lease — vehicles, machinery, equipment',  sort_order: 4610, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_RENT_LAND',                    description: 'Rent or lease — land, animals',                   sort_order: 4615, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_REPAIRS',                      description: 'Repairs and maintenance',                         sort_order: 4620, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_SEEDS_PLANTS',                 description: 'Seeds and plants',                                sort_order: 4625, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_STORAGE',                      description: 'Storage and warehousing',                         sort_order: 4630, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_SUPPLIES',                     description: 'Supplies',                                        sort_order: 4635, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_TAXES',                        description: 'Taxes',                                           sort_order: 4640, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_UTILITIES',                    description: 'Utilities',                                       sort_order: 4645, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_VETERINARY',                   description: 'Veterinary, breeding, and medicine',              sort_order: 4650, is_system: true },
    { return_form: '1040', activity_type: 'farm', tax_code: 'SF_OTHER_EXPENSES',               description: 'Other farm expenses',                             sort_order: 4655, is_system: true },

    // ─── 1040 Form 4835 farm_rental sort 4700-4899 ───────────────────────────
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_GROSS_FARM_RENTAL',  description: 'Gross farm rental income',                        sort_order: 4700, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_OTHER_INCOME',       description: 'Other income',                                    sort_order: 4705, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_CAR_TRUCK',          description: 'Car and truck expenses',                          sort_order: 4710, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_CHEMICALS',          description: 'Chemicals',                                       sort_order: 4715, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_CONSERVATION',       description: 'Conservation expenses',                           sort_order: 4720, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_CUSTOM_HIRE',        description: 'Custom hire (machine work)',                       sort_order: 4725, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_DEPRECIATION',       description: 'Depreciation and Section 179',                    sort_order: 4730, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_EMPLOYEE_BENEFITS',  description: 'Employee benefit programs',                       sort_order: 4735, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_FEED',               description: 'Feed',                                            sort_order: 4740, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_FERTILIZER',         description: 'Fertilizers and lime',                            sort_order: 4745, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_FREIGHT',            description: 'Freight and trucking',                            sort_order: 4750, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_GASOLINE',           description: 'Gasoline, fuel, and oil',                         sort_order: 4755, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_INSURANCE',          description: 'Insurance',                                       sort_order: 4760, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_MORTGAGE_INTEREST',  description: 'Mortgage interest',                               sort_order: 4765, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_OTHER_INTEREST',     description: 'Other interest',                                  sort_order: 4770, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_LABOR',              description: 'Labor hired',                                     sort_order: 4775, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_PENSION',            description: 'Pension and profit-sharing plans',                sort_order: 4780, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_RENT_MACHINERY',     description: 'Rent or lease — machinery and equipment',         sort_order: 4785, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_REPAIRS',            description: 'Repairs and maintenance',                         sort_order: 4790, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_SEEDS',              description: 'Seeds and plants',                                sort_order: 4795, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_STORAGE',            description: 'Storage and warehousing',                         sort_order: 4800, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_SUPPLIES',           description: 'Supplies',                                        sort_order: 4805, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_TAXES',              description: 'Taxes',                                           sort_order: 4810, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_UTILITIES',          description: 'Utilities',                                       sort_order: 4815, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_VETERINARY',         description: 'Veterinary, breeding, and medicine',              sort_order: 4820, is_system: true },
    { return_form: '1040', activity_type: 'farm_rental', tax_code: 'F4835_OTHER_EXPENSES',     description: 'Other farm rental expenses',                      sort_order: 4825, is_system: true },

    // ─── Common codes sort 9000-9099 ─────────────────────────────────────────
    { return_form: 'common', activity_type: 'common', tax_code: 'DONOTMAP',             description: 'Do Not Map — Exclude from Tax Return',   sort_order: 9000, is_system: true },
    { return_form: 'common', activity_type: 'common', tax_code: 'MEMO',                 description: 'Memo/Statistical Account',                sort_order: 9010, is_system: true },
    { return_form: 'common', activity_type: 'common', tax_code: 'INTERCOMPANY',         description: 'Intercompany/Eliminating Entry',          sort_order: 9020, is_system: true },
    { return_form: 'common', activity_type: 'common', tax_code: 'SUSPENSE',             description: 'Suspense Account',                        sort_order: 9030, is_system: true },
    { return_form: 'common', activity_type: 'common', tax_code: 'PRIOR_YEAR_ADJUSTMENT', description: 'Prior Year Adjustment',                  sort_order: 9040, is_system: true },
  ];

  for (const code of codes) {
    const [row] = await knex('tax_codes')
      .insert({ ...code, created_at: knex.fn.now(), updated_at: knex.fn.now() })
      .onConflict(['return_form', 'activity_type', 'tax_code'])
      .merge(['description', 'sort_order', 'is_system', 'updated_at'])
      .returning('id');

    const maps = softwareMapsFor(code.return_form, code.activity_type, code.tax_code);
    for (const map of maps) {
      await knex('tax_code_software_maps')
        .insert({ tax_code_id: row.id, ...map, created_at: knex.fn.now() })
        .onConflict(['tax_code_id', 'tax_software'])
        .merge(['software_code', 'software_description']);
    }
  }
};

/**
 * Returns software-specific code mappings for a given tax code.
 * Platforms: ultratax, cch, lacerte, gosystem, generic
 */
function softwareMapsFor(returnForm, activityType, taxCode) {
  const maps = [];

  // generic always maps 1:1
  maps.push({ tax_software: 'generic', software_code: taxCode, software_description: null });

  // ── 1120S business ──────────────────────────────────────────────────────────
  const s1120s = {
    // Page 1 Income
    S_GROSS_RECEIPTS:          { ut: '1120S-1a', cch: 'GR',    lac: '1a',   gs: 'GRS' },
    S_RETURNS_ALLOWANCES:      { ut: '1120S-1b', cch: 'RA',    lac: '1b',   gs: 'RTA' },
    S_COST_OF_GOODS_SOLD:      { ut: '1120S-2',  cch: 'COGS',  lac: '2',    gs: 'CGS' },
    S_GROSS_PROFIT:            { ut: '1120S-3',  cch: 'GP',    lac: '3',    gs: 'GPR' },
    S_NET_GAIN_4797:           { ut: '1120S-4',  cch: 'G4797', lac: '4',    gs: 'G47' },
    S_OTHER_INCOME:            { ut: '1120S-5',  cch: 'OI',    lac: '5',    gs: 'OTI' },
    // Page 1 Deductions
    S_COMPENSATION_OFFICERS:   { ut: '1120S-7',  cch: 'COFF',  lac: '7',    gs: 'COF' },
    S_SALARIES_WAGES:          { ut: '1120S-8',  cch: 'SAL',   lac: '8',    gs: 'SAL' },
    S_REPAIRS_MAINTENANCE:     { ut: '1120S-9',  cch: 'REP',   lac: '9',    gs: 'RPM' },
    S_BAD_DEBTS:               { ut: '1120S-10', cch: 'BD',    lac: '10',   gs: 'BDD' },
    S_RENTS:                   { ut: '1120S-11', cch: 'RNT',   lac: '11',   gs: 'RNT' },
    S_TAXES_LICENSES:          { ut: '1120S-12', cch: 'TXL',   lac: '12',   gs: 'TXL' },
    S_INTEREST_EXP:            { ut: '1120S-13', cch: 'INT',   lac: '13',   gs: 'INT' },
    S_DEPRECIATION:            { ut: '1120S-14', cch: 'DEP',   lac: '14',   gs: 'DEP' },
    S_DEPLETION:               { ut: '1120S-15', cch: 'DPL',   lac: '15',   gs: 'DPL' },
    S_ADVERTISING:             { ut: '1120S-16', cch: 'ADV',   lac: '16',   gs: 'ADV' },
    S_PENSION_PROFIT_SHARING:  { ut: '1120S-17', cch: 'PEN',   lac: '17',   gs: 'PEN' },
    S_EMPLOYEE_BENEFITS:       { ut: '1120S-18', cch: 'EBP',   lac: '18',   gs: 'EBP' },
    S_OTHER_DEDUCTIONS:        { ut: '1120S-19', cch: 'OD',    lac: '19',   gs: 'ODD' },
    // Schedule K
    S_K1_INTEREST_INCOME:      { ut: 'SK-4',     cch: 'KII',   lac: 'K4',   gs: 'KII' },
    S_K1_ORDINARY_DIVIDENDS:   { ut: 'SK-5a',    cch: 'KDIV',  lac: 'K5a',  gs: 'KOD' },
    S_K1_QUALIFIED_DIVIDENDS:  { ut: 'SK-5b',    cch: 'KQDIV', lac: 'K5b',  gs: 'KQD' },
    S_K1_ROYALTIES:            { ut: 'SK-6',     cch: 'KROY',  lac: 'K6',   gs: 'KRY' },
    S_K1_NET_ST_CAP_GAIN_LOSS: { ut: 'SK-7',     cch: 'KSTCG', lac: 'K7',   gs: 'KST' },
    S_K1_NET_LT_CAP_GAIN_LOSS: { ut: 'SK-8a',    cch: 'KLTCG', lac: 'K8a',  gs: 'KLT' },
    S_K1_UNRECAPTURED_1250:    { ut: 'SK-8b',    cch: 'K1250', lac: 'K8b',  gs: 'K12' },
    S_K1_NET_1231_GAIN_LOSS:   { ut: 'SK-9',     cch: 'K1231', lac: 'K9',   gs: 'K23' },
    S_K1_OTHER_INCOME_LOSS:    { ut: 'SK-10',    cch: 'KOIL',  lac: 'K10',  gs: 'KOI' },
    S_K1_SEC179_DEDUCTION:     { ut: 'SK-11',    cch: 'K179',  lac: 'K11',  gs: 'K17' },
    S_K1_CHARITABLE_CONTRIBUTIONS: { ut: 'SK-12a', cch: 'KCC', lac: 'K12a', gs: 'KCC' },
    S_K1_INVESTMENT_INTEREST:  { ut: 'SK-12b',   cch: 'KIEI',  lac: 'K12b', gs: 'KII2' },
    S_K1_FOREIGN_TAX_CREDIT:   { ut: 'SK-14a',   cch: 'KFTC',  lac: 'K14a', gs: 'KFT' },
    S_K1_AMT_ITEMS:            { ut: 'SK-15',    cch: 'KAMT',  lac: 'K15',  gs: 'KAM' },
    S_K1_OTHER_DEDUCTIONS:     { ut: 'SK-12d',   cch: 'KOD',   lac: 'K12d', gs: 'KOD2' },
    // Balance Sheet
    S_BS_CASH:                       { ut: 'SL-1',   cch: 'BCSH',  lac: 'L1',   gs: 'BCSH' },
    S_BS_TRADE_NOTES_AR:             { ut: 'SL-2a',  cch: 'BTAR',  lac: 'L2a',  gs: 'BTAR' },
    S_BS_INVENTORIES:                { ut: 'SL-3',   cch: 'BINV',  lac: 'L3',   gs: 'BINV' },
    S_BS_US_GOVT_OBLIGATIONS:        { ut: 'SL-4',   cch: 'BUSG',  lac: 'L4',   gs: 'BUSG' },
    S_BS_TAX_EXEMPT_SECURITIES:      { ut: 'SL-5',   cch: 'BTES',  lac: 'L5',   gs: 'BTES' },
    S_BS_OTHER_CURRENT_ASSETS:       { ut: 'SL-6',   cch: 'BOCA',  lac: 'L6',   gs: 'BOCA' },
    S_BS_LOANS_TO_SHAREHOLDERS:      { ut: 'SL-7',   cch: 'BLSH',  lac: 'L7',   gs: 'BLSH' },
    S_BS_MORTGAGE_REAL_ESTATE:       { ut: 'SL-8',   cch: 'BMRE',  lac: 'L8',   gs: 'BMRE' },
    S_BS_OTHER_INVESTMENTS:          { ut: 'SL-9',   cch: 'BOIN',  lac: 'L9',   gs: 'BOIN' },
    S_BS_BUILDINGS_LAND:             { ut: 'SL-10a', cch: 'BBLD',  lac: 'L10a', gs: 'BBLD' },
    S_BS_ACCUMULATED_DEPRECIATION:   { ut: 'SL-10b', cch: 'BACD',  lac: 'L10b', gs: 'BACD' },
    S_BS_LAND:                       { ut: 'SL-11',  cch: 'BLND',  lac: 'L11',  gs: 'BLND' },
    S_BS_INTANGIBLE_ASSETS:          { ut: 'SL-12a', cch: 'BINT',  lac: 'L12a', gs: 'BINT' },
    S_BS_ACCUMULATED_AMORTIZATION:   { ut: 'SL-12b', cch: 'BACA',  lac: 'L12b', gs: 'BACA' },
    S_BS_OTHER_ASSETS:               { ut: 'SL-13',  cch: 'BOAS',  lac: 'L13',  gs: 'BOAS' },
    S_BS_ACCOUNTS_PAYABLE:           { ut: 'SL-15',  cch: 'BAP',   lac: 'L15',  gs: 'BAP'  },
    S_BS_NOTES_PAYABLE_LT1YR:        { ut: 'SL-16',  cch: 'BNPLT', lac: 'L16',  gs: 'BNPL' },
    S_BS_OTHER_CURRENT_LIABILITIES:  { ut: 'SL-17',  cch: 'BOCL',  lac: 'L17',  gs: 'BOCL' },
    S_BS_LOANS_FROM_SHAREHOLDERS:    { ut: 'SL-18',  cch: 'BLFSH', lac: 'L18',  gs: 'BLFSH'},
    S_BS_MORTGAGES_GT1YR:            { ut: 'SL-19',  cch: 'BMGT',  lac: 'L19',  gs: 'BMGT' },
    S_BS_OTHER_LIABILITIES:          { ut: 'SL-20',  cch: 'BOLT',  lac: 'L20',  gs: 'BOLT' },
    S_BS_CAPITAL_STOCK:              { ut: 'SL-22',  cch: 'BCST',  lac: 'L22',  gs: 'BCST' },
    S_BS_ADDITIONAL_PAID_IN_CAPITAL: { ut: 'SL-23',  cch: 'BAPIC', lac: 'L23',  gs: 'BAPIC'},
    S_BS_AAA:                        { ut: 'SL-24',  cch: 'BAAA',  lac: 'L24',  gs: 'BAAA' },
    S_BS_OAA:                        { ut: 'SL-25',  cch: 'BOAA',  lac: 'L25',  gs: 'BOAA' },
    S_BS_RETAINED_EARNINGS_PTI:      { ut: 'SL-26',  cch: 'BREP',  lac: 'L26',  gs: 'BREP' },
    S_BS_LESS_TREASURY_STOCK:        { ut: 'SL-27',  cch: 'BTRE',  lac: 'L27',  gs: 'BTRE' },
    // M-1
    S_M1_NET_INCOME_PER_BOOKS:        { ut: 'SM1-1',  cch: 'M1NI',  lac: 'M1-1',  gs: 'M1NI'  },
    S_M1_INCOME_RETURN_NOT_BOOKS:     { ut: 'SM1-2',  cch: 'M1IRB', lac: 'M1-2',  gs: 'M1IRB' },
    S_M1_EXPENSES_BOOKS_NOT_RETURN:   { ut: 'SM1-3',  cch: 'M1EBR', lac: 'M1-3',  gs: 'M1EBR' },
    S_M1_INCOME_BOOKS_NOT_RETURN:     { ut: 'SM1-4',  cch: 'M1IBR', lac: 'M1-4',  gs: 'M1IBR' },
    S_M1_DEDUCTIONS_RETURN_NOT_BOOKS: { ut: 'SM1-5',  cch: 'M1DRB', lac: 'M1-5',  gs: 'M1DRB' },
    // M-2
    S_M2_AAA_BEGINNING:         { ut: 'SM2-1a',  cch: 'M2AB',  lac: 'M2A1',  gs: 'M2AB' },
    S_M2_AAA_ORDINARY_INCOME:   { ut: 'SM2-1b',  cch: 'M2AOI', lac: 'M2A2',  gs: 'M2AOI'},
    S_M2_AAA_OTHER_ADDITIONS:   { ut: 'SM2-1c',  cch: 'M2AOA', lac: 'M2A3',  gs: 'M2AOA'},
    S_M2_AAA_LOSSES_DEDUCTIONS: { ut: 'SM2-1d',  cch: 'M2ALD', lac: 'M2A4',  gs: 'M2ALD'},
    S_M2_AAA_OTHER_REDUCTIONS:  { ut: 'SM2-1e',  cch: 'M2AOR', lac: 'M2A5',  gs: 'M2AOR'},
    S_M2_AAA_DISTRIBUTIONS:     { ut: 'SM2-1f',  cch: 'M2AD',  lac: 'M2A6',  gs: 'M2AD' },
    S_M2_OAA_BEGINNING:         { ut: 'SM2-2a',  cch: 'M2OB',  lac: 'M2O1',  gs: 'M2OB' },
    S_M2_OAA_INCREASES:         { ut: 'SM2-2b',  cch: 'M2OI',  lac: 'M2O2',  gs: 'M2OI' },
    S_M2_OAA_DECREASES:         { ut: 'SM2-2c',  cch: 'M2OD',  lac: 'M2O3',  gs: 'M2OD' },
  };

  // ── 1120S rental ────────────────────────────────────────────────────────────
  const s1120sRental = {
    RENTAL_GROSS_RENTS:          { ut: 'SR-3',   cch: 'RGR',  lac: 'RE3',  gs: 'RGR'  },
    RENTAL_OTHER_INCOME:         { ut: 'SR-4',   cch: 'ROI',  lac: 'RE4',  gs: 'ROI'  },
    RENTAL_ADVERTISING:          { ut: 'SR-5a',  cch: 'RADV', lac: 'RE5a', gs: 'RADV' },
    RENTAL_AUTO_TRAVEL:          { ut: 'SR-5b',  cch: 'RAUT', lac: 'RE5b', gs: 'RAUT' },
    RENTAL_CLEANING_MAINTENANCE: { ut: 'SR-5c',  cch: 'RCLN', lac: 'RE5c', gs: 'RCLN' },
    RENTAL_COMMISSIONS:          { ut: 'SR-5d',  cch: 'RCOM', lac: 'RE5d', gs: 'RCOM' },
    RENTAL_INSURANCE:            { ut: 'SR-5e',  cch: 'RINS', lac: 'RE5e', gs: 'RINS' },
    RENTAL_LEGAL_PROFESSIONAL:   { ut: 'SR-5f',  cch: 'RLGL', lac: 'RE5f', gs: 'RLGL' },
    RENTAL_MANAGEMENT_FEES:      { ut: 'SR-5g',  cch: 'RMGT', lac: 'RE5g', gs: 'RMGT' },
    RENTAL_MORTGAGE_INTEREST:    { ut: 'SR-5h',  cch: 'RMIN', lac: 'RE5h', gs: 'RMIN' },
    RENTAL_OTHER_INTEREST:       { ut: 'SR-5i',  cch: 'ROIN', lac: 'RE5i', gs: 'ROIN' },
    RENTAL_REPAIRS:              { ut: 'SR-5j',  cch: 'RREP', lac: 'RE5j', gs: 'RREP' },
    RENTAL_SUPPLIES:             { ut: 'SR-5k',  cch: 'RSUP', lac: 'RE5k', gs: 'RSUP' },
    RENTAL_TAXES:                { ut: 'SR-5l',  cch: 'RTAX', lac: 'RE5l', gs: 'RTAX' },
    RENTAL_UTILITIES:            { ut: 'SR-5m',  cch: 'RUTI', lac: 'RE5m', gs: 'RUTI' },
    RENTAL_DEPRECIATION:         { ut: 'SR-5n',  cch: 'RDEP', lac: 'RE5n', gs: 'RDEP' },
    RENTAL_OTHER_EXPENSES:       { ut: 'SR-5o',  cch: 'ROEX', lac: 'RE5o', gs: 'ROEX' },
  };

  // ── 1120S farm ──────────────────────────────────────────────────────────────
  const s1120sFarm = {
    FARM_SALES_LIVESTOCK_PRODUCTS: { ut: 'SF-1a',  cch: 'FSLP', lac: 'F1a',  gs: 'FSLP' },
    FARM_COST_BASIS_LIVESTOCK:     { ut: 'SF-1b',  cch: 'FCBL', lac: 'F1b',  gs: 'FCBL' },
    FARM_OTHER_FARM_INCOME:        { ut: 'SF-2',   cch: 'FOFI', lac: 'F2',   gs: 'FOFI' },
    FARM_AG_PROGRAM_PAYMENTS:      { ut: 'SF-4a',  cch: 'FAPP', lac: 'F4a',  gs: 'FAPP' },
    FARM_CCC_LOANS:                { ut: 'SF-5a',  cch: 'FCCL', lac: 'F5a',  gs: 'FCCL' },
    FARM_CROP_INSURANCE:           { ut: 'SF-6a',  cch: 'FCRI', lac: 'F6a',  gs: 'FCRI' },
    FARM_CUSTOM_HIRE_INCOME:       { ut: 'SF-7',   cch: 'FCHI', lac: 'F7',   gs: 'FCHI' },
    FARM_CAR_TRUCK:                { ut: 'SF-10',  cch: 'FCAR', lac: 'F10',  gs: 'FCAR' },
    FARM_CHEMICALS:                { ut: 'SF-11',  cch: 'FCHM', lac: 'F11',  gs: 'FCHM' },
    FARM_CONSERVATION:             { ut: 'SF-12',  cch: 'FCON', lac: 'F12',  gs: 'FCON' },
    FARM_CUSTOM_HIRE_EXP:          { ut: 'SF-13',  cch: 'FCHE', lac: 'F13',  gs: 'FCHE' },
    FARM_DEPRECIATION:             { ut: 'SF-14',  cch: 'FDEP', lac: 'F14',  gs: 'FDEP' },
    FARM_EMPLOYEE_BENEFITS:        { ut: 'SF-15',  cch: 'FEBP', lac: 'F15',  gs: 'FEBP' },
    FARM_FEED:                     { ut: 'SF-16',  cch: 'FFED', lac: 'F16',  gs: 'FFED' },
    FARM_FERTILIZER:               { ut: 'SF-17',  cch: 'FFER', lac: 'F17',  gs: 'FFER' },
    FARM_FREIGHT_TRUCKING:         { ut: 'SF-18',  cch: 'FFRT', lac: 'F18',  gs: 'FFRT' },
    FARM_GASOLINE_FUEL:            { ut: 'SF-19',  cch: 'FGAS', lac: 'F19',  gs: 'FGAS' },
    FARM_INSURANCE:                { ut: 'SF-20',  cch: 'FINS', lac: 'F20',  gs: 'FINS' },
    FARM_MORTGAGE_INTEREST:        { ut: 'SF-21a', cch: 'FMIN', lac: 'F21a', gs: 'FMIN' },
    FARM_OTHER_INTEREST:           { ut: 'SF-21b', cch: 'FOIN', lac: 'F21b', gs: 'FOIN' },
    FARM_LABOR_HIRED:              { ut: 'SF-22',  cch: 'FLBR', lac: 'F22',  gs: 'FLBR' },
    FARM_PENSION:                  { ut: 'SF-23',  cch: 'FPEN', lac: 'F23',  gs: 'FPEN' },
    FARM_RENT_MACHINERY:           { ut: 'SF-24a', cch: 'FRMM', lac: 'F24a', gs: 'FRMM' },
    FARM_RENT_LAND:                { ut: 'SF-24b', cch: 'FRML', lac: 'F24b', gs: 'FRML' },
    FARM_REPAIRS:                  { ut: 'SF-25',  cch: 'FREP', lac: 'F25',  gs: 'FREP' },
    FARM_SEEDS_PLANTS:             { ut: 'SF-26',  cch: 'FSED', lac: 'F26',  gs: 'FSED' },
    FARM_STORAGE:                  { ut: 'SF-27',  cch: 'FSTR', lac: 'F27',  gs: 'FSTR' },
    FARM_SUPPLIES:                 { ut: 'SF-28',  cch: 'FSUP', lac: 'F28',  gs: 'FSUP' },
    FARM_TAXES:                    { ut: 'SF-29',  cch: 'FTAX', lac: 'F29',  gs: 'FTAX' },
    FARM_UTILITIES:                { ut: 'SF-30',  cch: 'FUTI', lac: 'F30',  gs: 'FUTI' },
    FARM_VETERINARY:               { ut: 'SF-31',  cch: 'FVET', lac: 'F31',  gs: 'FVET' },
    FARM_OTHER_EXPENSES:           { ut: 'SF-32',  cch: 'FOEX', lac: 'F32',  gs: 'FOEX' },
  };

  // ── 1120S farm_rental ───────────────────────────────────────────────────────
  const s1120sFarmRental = {
    FR_GROSS_FARM_RENTAL: { ut: 'FR-2',   cch: 'FRGR', lac: 'FR2',   gs: 'FRGR' },
    FR_OTHER_INCOME:      { ut: 'FR-3',   cch: 'FROI', lac: 'FR3',   gs: 'FROI' },
    FR_CAR_TRUCK:         { ut: 'FR-6a',  cch: 'FRCT', lac: 'FR6a',  gs: 'FRCT' },
    FR_CHEMICALS:         { ut: 'FR-6b',  cch: 'FRCH', lac: 'FR6b',  gs: 'FRCH' },
    FR_CONSERVATION:      { ut: 'FR-6c',  cch: 'FRCN', lac: 'FR6c',  gs: 'FRCN' },
    FR_CUSTOM_HIRE:       { ut: 'FR-6d',  cch: 'FRCU', lac: 'FR6d',  gs: 'FRCU' },
    FR_DEPRECIATION:      { ut: 'FR-6e',  cch: 'FRDP', lac: 'FR6e',  gs: 'FRDP' },
    FR_EMPLOYEE_BENEFITS: { ut: 'FR-6f',  cch: 'FREB', lac: 'FR6f',  gs: 'FREB' },
    FR_FEED:              { ut: 'FR-6g',  cch: 'FRFD', lac: 'FR6g',  gs: 'FRFD' },
    FR_FERTILIZER:        { ut: 'FR-6h',  cch: 'FRFE', lac: 'FR6h',  gs: 'FRFE' },
    FR_FREIGHT:           { ut: 'FR-6i',  cch: 'FRFR', lac: 'FR6i',  gs: 'FRFR' },
    FR_GASOLINE:          { ut: 'FR-6j',  cch: 'FRGS', lac: 'FR6j',  gs: 'FRGS' },
    FR_INSURANCE:         { ut: 'FR-6k',  cch: 'FRIN', lac: 'FR6k',  gs: 'FRIN' },
    FR_MORTGAGE_INTEREST: { ut: 'FR-6l',  cch: 'FRMI', lac: 'FR6l',  gs: 'FRMI' },
    FR_OTHER_INTEREST:    { ut: 'FR-6m',  cch: 'FROI2',lac: 'FR6m',  gs: 'FROI2'},
    FR_LABOR:             { ut: 'FR-6n',  cch: 'FRLB', lac: 'FR6n',  gs: 'FRLB' },
    FR_PENSION:           { ut: 'FR-6o',  cch: 'FRPN', lac: 'FR6o',  gs: 'FRPN' },
    FR_RENT_MACHINERY:    { ut: 'FR-6p',  cch: 'FRRM', lac: 'FR6p',  gs: 'FRRM' },
    FR_REPAIRS:           { ut: 'FR-6q',  cch: 'FRRP', lac: 'FR6q',  gs: 'FRRP' },
    FR_SEEDS:             { ut: 'FR-6r',  cch: 'FRSD', lac: 'FR6r',  gs: 'FRSD' },
    FR_STORAGE:           { ut: 'FR-6s',  cch: 'FRST', lac: 'FR6s',  gs: 'FRST' },
    FR_SUPPLIES:          { ut: 'FR-6t',  cch: 'FRSU', lac: 'FR6t',  gs: 'FRSU' },
    FR_TAXES:             { ut: 'FR-6u',  cch: 'FRTX', lac: 'FR6u',  gs: 'FRTX' },
    FR_UTILITIES:         { ut: 'FR-6v',  cch: 'FRUL', lac: 'FR6v',  gs: 'FRUL' },
    FR_VETERINARY:        { ut: 'FR-6w',  cch: 'FRVE', lac: 'FR6w',  gs: 'FRVE' },
    FR_OTHER_EXPENSES:    { ut: 'FR-6x',  cch: 'FROX', lac: 'FR6x',  gs: 'FROX' },
  };

  // ── 1040 Schedule C ─────────────────────────────────────────────────────────
  const sc1040 = {
    SC_GROSS_RECEIPTS:         { ut: 'C-1',    cch: 'CGR',  lac: 'C1',    gs: 'CGR'  },
    SC_RETURNS_ALLOWANCES:     { ut: 'C-2',    cch: 'CRA',  lac: 'C2',    gs: 'CRA'  },
    SC_COST_OF_GOODS_SOLD:     { ut: 'C-4',    cch: 'CCOG', lac: 'C4',    gs: 'CCOG' },
    SC_OTHER_INCOME:           { ut: 'C-6',    cch: 'COI',  lac: 'C6',    gs: 'COI'  },
    SC_ADVERTISING:            { ut: 'C-8',    cch: 'CADV', lac: 'C8',    gs: 'CADV' },
    SC_CAR_TRUCK:              { ut: 'C-9',    cch: 'CCAR', lac: 'C9',    gs: 'CCAR' },
    SC_COMMISSIONS_FEES:       { ut: 'C-10',   cch: 'CCOM', lac: 'C10',   gs: 'CCOM' },
    SC_CONTRACT_LABOR:         { ut: 'C-11',   cch: 'CCON', lac: 'C11',   gs: 'CCON' },
    SC_DEPLETION:              { ut: 'C-12',   cch: 'CDPL', lac: 'C12',   gs: 'CDPL' },
    SC_DEPRECIATION:           { ut: 'C-13',   cch: 'CDEP', lac: 'C13',   gs: 'CDEP' },
    SC_EMPLOYEE_BENEFITS:      { ut: 'C-14',   cch: 'CEBP', lac: 'C14',   gs: 'CEBP' },
    SC_INSURANCE:              { ut: 'C-15',   cch: 'CINS', lac: 'C15',   gs: 'CINS' },
    SC_MORTGAGE_INTEREST:      { ut: 'C-16a',  cch: 'CMIN', lac: 'C16a',  gs: 'CMIN' },
    SC_OTHER_INTEREST:         { ut: 'C-16b',  cch: 'COIN', lac: 'C16b',  gs: 'COIN' },
    SC_LEGAL_PROFESSIONAL:     { ut: 'C-17',   cch: 'CLGL', lac: 'C17',   gs: 'CLGL' },
    SC_OFFICE_EXPENSE:         { ut: 'C-18',   cch: 'COFF', lac: 'C18',   gs: 'COFF' },
    SC_PENSION_PROFIT_SHARING: { ut: 'C-19',   cch: 'CPEN', lac: 'C19',   gs: 'CPEN' },
    SC_RENT_LEASE_VEHICLES:    { ut: 'C-20a',  cch: 'CRLV', lac: 'C20a',  gs: 'CRLV' },
    SC_RENT_LEASE_OTHER:       { ut: 'C-20b',  cch: 'CRLO', lac: 'C20b',  gs: 'CRLO' },
    SC_REPAIRS_MAINTENANCE:    { ut: 'C-21',   cch: 'CREP', lac: 'C21',   gs: 'CREP' },
    SC_SUPPLIES:               { ut: 'C-22',   cch: 'CSUP', lac: 'C22',   gs: 'CSUP' },
    SC_TAXES_LICENSES:         { ut: 'C-23',   cch: 'CTAX', lac: 'C23',   gs: 'CTAX' },
    SC_TRAVEL:                 { ut: 'C-24a',  cch: 'CTRV', lac: 'C24a',  gs: 'CTRV' },
    SC_MEALS_50PCT:            { ut: 'C-24b',  cch: 'CMEL', lac: 'C24b',  gs: 'CMEL' },
    SC_UTILITIES:              { ut: 'C-25',   cch: 'CUTI', lac: 'C25',   gs: 'CUTI' },
    SC_WAGES:                  { ut: 'C-26',   cch: 'CWAG', lac: 'C26',   gs: 'CWAG' },
    SC_OTHER_EXPENSES:         { ut: 'C-27a',  cch: 'COEX', lac: 'C27a',  gs: 'COEX' },
  };

  // ── 1040 Schedule E ─────────────────────────────────────────────────────────
  const se1040 = {
    SE_RENTS_RECEIVED:       { ut: 'E-3',   cch: 'ERNT', lac: 'E3',   gs: 'ERNT' },
    SE_ROYALTIES_RECEIVED:   { ut: 'E-4',   cch: 'EROY', lac: 'E4',   gs: 'EROY' },
    SE_ADVERTISING:          { ut: 'E-5',   cch: 'EADV', lac: 'E5',   gs: 'EADV' },
    SE_AUTO_TRAVEL:          { ut: 'E-6',   cch: 'EAUT', lac: 'E6',   gs: 'EAUT' },
    SE_CLEANING_MAINTENANCE: { ut: 'E-7',   cch: 'ECLN', lac: 'E7',   gs: 'ECLN' },
    SE_COMMISSIONS:          { ut: 'E-8',   cch: 'ECOM', lac: 'E8',   gs: 'ECOM' },
    SE_INSURANCE:            { ut: 'E-9',   cch: 'EINS', lac: 'E9',   gs: 'EINS' },
    SE_LEGAL_PROFESSIONAL:   { ut: 'E-10',  cch: 'ELGL', lac: 'E10',  gs: 'ELGL' },
    SE_MANAGEMENT_FEES:      { ut: 'E-11',  cch: 'EMGT', lac: 'E11',  gs: 'EMGT' },
    SE_MORTGAGE_INTEREST:    { ut: 'E-12',  cch: 'EMIN', lac: 'E12',  gs: 'EMIN' },
    SE_OTHER_INTEREST:       { ut: 'E-13',  cch: 'EOIN', lac: 'E13',  gs: 'EOIN' },
    SE_REPAIRS:              { ut: 'E-14',  cch: 'EREP', lac: 'E14',  gs: 'EREP' },
    SE_SUPPLIES:             { ut: 'E-15',  cch: 'ESUP', lac: 'E15',  gs: 'ESUP' },
    SE_TAXES:                { ut: 'E-16',  cch: 'ETAX', lac: 'E16',  gs: 'ETAX' },
    SE_UTILITIES:            { ut: 'E-17',  cch: 'EUTI', lac: 'E17',  gs: 'EUTI' },
    SE_DEPRECIATION:         { ut: 'E-18',  cch: 'EDEP', lac: 'E18',  gs: 'EDEP' },
    SE_OTHER_EXPENSES:       { ut: 'E-19',  cch: 'EOEX', lac: 'E19',  gs: 'EOEX' },
  };

  // ── 1040 Schedule F ─────────────────────────────────────────────────────────
  const sf1040 = {
    SF_SALES_LIVESTOCK_PRODUCTS: { ut: 'F-1a',  cch: 'FSLP', lac: 'F1a',  gs: 'FSLP' },
    SF_COST_BASIS_LIVESTOCK:     { ut: 'F-1b',  cch: 'FCBL', lac: 'F1b',  gs: 'FCBL' },
    SF_OTHER_FARM_INCOME:        { ut: 'F-2',   cch: 'FOFI', lac: 'F2',   gs: 'FOFI' },
    SF_AG_PROGRAM_PAYMENTS:      { ut: 'F-4a',  cch: 'FAPP', lac: 'F4a',  gs: 'FAPP' },
    SF_CCC_LOANS:                { ut: 'F-5a',  cch: 'FCCL', lac: 'F5a',  gs: 'FCCL' },
    SF_CROP_INSURANCE:           { ut: 'F-6a',  cch: 'FCRI', lac: 'F6a',  gs: 'FCRI' },
    SF_CUSTOM_HIRE_INCOME:       { ut: 'F-7',   cch: 'FCHI', lac: 'F7',   gs: 'FCHI' },
    SF_CAR_TRUCK:                { ut: 'F-10',  cch: 'FCAR', lac: 'F10',  gs: 'FCAR' },
    SF_CHEMICALS:                { ut: 'F-11',  cch: 'FCHM', lac: 'F11',  gs: 'FCHM' },
    SF_CONSERVATION:             { ut: 'F-12',  cch: 'FCON', lac: 'F12',  gs: 'FCON' },
    SF_CUSTOM_HIRE_EXP:          { ut: 'F-13',  cch: 'FCHE', lac: 'F13',  gs: 'FCHE' },
    SF_DEPRECIATION:             { ut: 'F-14',  cch: 'FDEP', lac: 'F14',  gs: 'FDEP' },
    SF_EMPLOYEE_BENEFITS:        { ut: 'F-15',  cch: 'FEBP', lac: 'F15',  gs: 'FEBP' },
    SF_FEED:                     { ut: 'F-16',  cch: 'FFED', lac: 'F16',  gs: 'FFED' },
    SF_FERTILIZER:               { ut: 'F-17',  cch: 'FFER', lac: 'F17',  gs: 'FFER' },
    SF_FREIGHT_TRUCKING:         { ut: 'F-18',  cch: 'FFRT', lac: 'F18',  gs: 'FFRT' },
    SF_GASOLINE_FUEL:            { ut: 'F-19',  cch: 'FGAS', lac: 'F19',  gs: 'FGAS' },
    SF_INSURANCE:                { ut: 'F-20',  cch: 'FINS', lac: 'F20',  gs: 'FINS' },
    SF_MORTGAGE_INTEREST:        { ut: 'F-21a', cch: 'FMIN', lac: 'F21a', gs: 'FMIN' },
    SF_OTHER_INTEREST:           { ut: 'F-21b', cch: 'FOIN', lac: 'F21b', gs: 'FOIN' },
    SF_LABOR_HIRED:              { ut: 'F-22',  cch: 'FLBR', lac: 'F22',  gs: 'FLBR' },
    SF_PENSION:                  { ut: 'F-23',  cch: 'FPEN', lac: 'F23',  gs: 'FPEN' },
    SF_RENT_MACHINERY:           { ut: 'F-24a', cch: 'FRMM', lac: 'F24a', gs: 'FRMM' },
    SF_RENT_LAND:                { ut: 'F-24b', cch: 'FRML', lac: 'F24b', gs: 'FRML' },
    SF_REPAIRS:                  { ut: 'F-25',  cch: 'FREP', lac: 'F25',  gs: 'FREP' },
    SF_SEEDS_PLANTS:             { ut: 'F-26',  cch: 'FSED', lac: 'F26',  gs: 'FSED' },
    SF_STORAGE:                  { ut: 'F-27',  cch: 'FSTR', lac: 'F27',  gs: 'FSTR' },
    SF_SUPPLIES:                 { ut: 'F-28',  cch: 'FSUP', lac: 'F28',  gs: 'FSUP' },
    SF_TAXES:                    { ut: 'F-29',  cch: 'FTAX', lac: 'F29',  gs: 'FTAX' },
    SF_UTILITIES:                { ut: 'F-30',  cch: 'FUTI', lac: 'F30',  gs: 'FUTI' },
    SF_VETERINARY:               { ut: 'F-31',  cch: 'FVET', lac: 'F31',  gs: 'FVET' },
    SF_OTHER_EXPENSES:           { ut: 'F-32',  cch: 'FOEX', lac: 'F32',  gs: 'FOEX' },
  };

  // ── 1040 Form 4835 ──────────────────────────────────────────────────────────
  const f4835 = {
    F4835_GROSS_FARM_RENTAL: { ut: '4835-2',   cch: '4GFR', lac: '48-2',   gs: '4GFR' },
    F4835_OTHER_INCOME:      { ut: '4835-3',   cch: '4OI',  lac: '48-3',   gs: '4OI'  },
    F4835_CAR_TRUCK:         { ut: '4835-10',  cch: '4CT',  lac: '48-10',  gs: '4CT'  },
    F4835_CHEMICALS:         { ut: '4835-11',  cch: '4CH',  lac: '48-11',  gs: '4CH'  },
    F4835_CONSERVATION:      { ut: '4835-12',  cch: '4CN',  lac: '48-12',  gs: '4CN'  },
    F4835_CUSTOM_HIRE:       { ut: '4835-13',  cch: '4CU',  lac: '48-13',  gs: '4CU'  },
    F4835_DEPRECIATION:      { ut: '4835-14',  cch: '4DP',  lac: '48-14',  gs: '4DP'  },
    F4835_EMPLOYEE_BENEFITS: { ut: '4835-15',  cch: '4EB',  lac: '48-15',  gs: '4EB'  },
    F4835_FEED:              { ut: '4835-16',  cch: '4FD',  lac: '48-16',  gs: '4FD'  },
    F4835_FERTILIZER:        { ut: '4835-17',  cch: '4FE',  lac: '48-17',  gs: '4FE'  },
    F4835_FREIGHT:           { ut: '4835-18',  cch: '4FR',  lac: '48-18',  gs: '4FR'  },
    F4835_GASOLINE:          { ut: '4835-19',  cch: '4GS',  lac: '48-19',  gs: '4GS'  },
    F4835_INSURANCE:         { ut: '4835-20',  cch: '4IN',  lac: '48-20',  gs: '4IN'  },
    F4835_MORTGAGE_INTEREST: { ut: '4835-21a', cch: '4MI',  lac: '48-21a', gs: '4MI'  },
    F4835_OTHER_INTEREST:    { ut: '4835-21b', cch: '4OIN', lac: '48-21b', gs: '4OIN' },
    F4835_LABOR:             { ut: '4835-22',  cch: '4LB',  lac: '48-22',  gs: '4LB'  },
    F4835_PENSION:           { ut: '4835-23',  cch: '4PN',  lac: '48-23',  gs: '4PN'  },
    F4835_RENT_MACHINERY:    { ut: '4835-24',  cch: '4RM',  lac: '48-24',  gs: '4RM'  },
    F4835_REPAIRS:           { ut: '4835-25',  cch: '4RP',  lac: '48-25',  gs: '4RP'  },
    F4835_SEEDS:             { ut: '4835-26',  cch: '4SD',  lac: '48-26',  gs: '4SD'  },
    F4835_STORAGE:           { ut: '4835-27',  cch: '4ST',  lac: '48-27',  gs: '4ST'  },
    F4835_SUPPLIES:          { ut: '4835-28',  cch: '4SU',  lac: '48-28',  gs: '4SU'  },
    F4835_TAXES:             { ut: '4835-29',  cch: '4TX',  lac: '48-29',  gs: '4TX'  },
    F4835_UTILITIES:         { ut: '4835-30',  cch: '4UT',  lac: '48-30',  gs: '4UT'  },
    F4835_VETERINARY:        { ut: '4835-31',  cch: '4VT',  lac: '48-31',  gs: '4VT'  },
    F4835_OTHER_EXPENSES:    { ut: '4835-32',  cch: '4OE',  lac: '48-32',  gs: '4OE'  },
  };

  // ── Common ──────────────────────────────────────────────────────────────────
  const common = {
    DONOTMAP:             { ut: 'DONOTMAP',   cch: 'DNM',  lac: 'DNM',  gs: 'DNM'  },
    MEMO:                 { ut: 'MEMO',       cch: 'MEMO', lac: 'MEMO', gs: 'MEMO' },
    INTERCOMPANY:         { ut: 'INTERCO',    cch: 'ICO',  lac: 'ICO',  gs: 'ICO'  },
    SUSPENSE:             { ut: 'SUSPENSE',   cch: 'SUS',  lac: 'SUS',  gs: 'SUS'  },
    PRIOR_YEAR_ADJUSTMENT:{ ut: 'PYA',        cch: 'PYA',  lac: 'PYA',  gs: 'PYA'  },
  };

  // Combine all lookup tables
  const allMaps = Object.assign({}, s1120s, s1120sRental, s1120sFarm, s1120sFarmRental,
                                    sc1040, se1040, sf1040, f4835, common);

  const entry = allMaps[taxCode];
  if (entry) {
    maps.push({ tax_software: 'ultratax',  software_code: entry.ut,  software_description: null });
    maps.push({ tax_software: 'cch',       software_code: entry.cch, software_description: null });
    maps.push({ tax_software: 'lacerte',   software_code: entry.lac, software_description: null });
    maps.push({ tax_software: 'gosystem',  software_code: entry.gs,  software_description: null });
  }

  return maps;
}
